name: build-report

on:

  push:
    branches: [main, dev]
    paths:
      - 'deliverables/report/**'

  pull_request:
    branches: [main, dev]
    paths:
      - 'deliverables/report/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Report

        uses: xu-cheng/latex-action@v3
        
        with:
          working_directory: deliverables/report
          root_file: latex/ld2022-report.tex
          latexmk_use_lualatex: false
          args: -pdf -cd -jobname=ld2022-report -outdir=../../